TWITTER_MODEL = "cardiffnlp/twitter-xlm-roberta-base-sentiment"
TWITTER_FUNCTION = "sentiment-analysis"
REDDIT_MODEL = "j-hartmann/sentiment-roberta-large-english-3-classes"
REDDIT_FUNCTION = "text-classification"
GOOGLE_MODEL = "siebert/sentiment-roberta-large-english"
GOOGLE_FUNCTION = "sentiment-analysis"
