TWITTER_MODEL = "cardiffnlp/twitter-roberta-base-sentiment-latest"
TWITTER_FUNCTION = "sentiment-analysis"
REDDIT_MODEL = "j-hartmann/sentiment-roberta-large-english-3-classes"
REDDIT_FUNCTION = "text-classification"
# GOOGLE_MODEL = "siebert/sentiment-roberta-large-english"
# GOOGLE_FUNCTION = "sentiment-analysis"
GOOGLE_MODEL = "tahamueed23/english-sentiment-roberta-large"
GOOGLE_FUNCTION = "sentiment-analysis"
